### ISSUE TITLE
ShuffleMCQ benchmark

### ISSUE THREAD

**Issue by chaitanya100100** [facebookresearch/HierVL#11]
Hello,
Where can I find ShuffleMCQ benchmark data? It would be great if you can provide it to compare with HierVL.
Thanks.

**Comment by thechargedneutron** [comment]
Hi @chaitanya100100 , thanks for the interest in our work. Since this is a pretraining evaluation, we did not create a separate benchmark for ShuffleMCQ. We simply randomize the clips for every input for SummaryMCQ. Here is the relevant line of code: https://github.com/facebookresearch/HierVL/blob/998a8527ed6a3306e031ee73ed81978db6e99861/trainer/trainer_egoaggregate.py#L429

The incorrect options are just a random permutation of clips in the correct frame. If you really want to get the exact same seed, you can probably run this code and save the outputs and then use it in your evaluation OR simply use the same logic in your evaluation and report.

**Comment by chaitanya100100** [comment]
Thanks for the quick response! I will probably use the same logic in my code and make sure that the evaluation is robust by trying out multiple random seeds.

**Comment by thechargedneutron** [comment]
Yeah that is perfect, thanks!

Let me know if you have other questions.
